name: Build Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '.eslintrc.json'
      - '.github/workflows/*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.ts'
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Compile TypeScript
        run: npm run compile
