name: Extension CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '.eslintrc.json'
      - '.github/workflows/*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      NODE_ENV: development


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile
