name: Publish Extension
run-name: Publish Extension ${{ inputs.publish }} Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Print the input version to STDOUT
        run: echo  The tags are ${{ inputs.publish }}
