name: Publish Extension
run-name: Publish Extension ${{ inputs.version }} Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --global vsce
      - run: npm install
      - run: |
          node scripts/publish.mjs ${{ inputs.version }} && vsce publish ${{ inputs.version }} -p ${{ secrets.EXTENSION_TOKEN }}
      - run: git push origin HEAD
