name: Publish Extension
run-name: Publish Extension ${{ inputs.version }} Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          sudo apt-get install -y libsecret-1-dev
          npm install --global vsce
      - run: npm install
      - run: echo $EXTENSION_TOKEN | vsce login $EXTENSION_PUBLISHER
        env:
          EXTENSION_PUBLISHER: ${{ secrets.EXTENSION_PUBLISHER }}
          EXTENSION_TOKEN: ${{ secrets.EXTENSION_TOKEN }}
      - run: npm run publish -- ${{ inputs.version }}
      - run: git push origin HEAD
